In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data=genfromtxt("../DATA/bank_note_data.txt",delimiter=",")

In [3]:
data


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
#0 MEANS FORTREE AND 1 MEANS AUTHENTIC
labels=data[:,4]


In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features=data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X=features
y=labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_test.max()

17.1116

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler_object= MinMaxScaler()

In [14]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [15]:
scaled_X_train=scaler_object.transform(X_train)

In [16]:
scaled_X_test= scaler_object.transform(X_test)

In [17]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))


In [20]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [21]:
model.fit(scaled_X_train,y_train,epochs=70,verbose=2)

Epoch 1/70
29/29 - 1s - loss: 0.6952 - accuracy: 0.5539
Epoch 2/70
29/29 - 0s - loss: 0.6929 - accuracy: 0.5669
Epoch 3/70
29/29 - 0s - loss: 0.6914 - accuracy: 0.5713
Epoch 4/70
29/29 - 0s - loss: 0.6899 - accuracy: 0.5724
Epoch 5/70
29/29 - 0s - loss: 0.6884 - accuracy: 0.5854
Epoch 6/70
29/29 - 0s - loss: 0.6862 - accuracy: 0.6170
Epoch 7/70
29/29 - 0s - loss: 0.6830 - accuracy: 0.6333
Epoch 8/70
29/29 - 0s - loss: 0.6797 - accuracy: 0.6518
Epoch 9/70
29/29 - 0s - loss: 0.6761 - accuracy: 0.6507
Epoch 10/70
29/29 - 0s - loss: 0.6721 - accuracy: 0.6409
Epoch 11/70
29/29 - 0s - loss: 0.6678 - accuracy: 0.6409
Epoch 12/70
29/29 - 0s - loss: 0.6633 - accuracy: 0.6551
Epoch 13/70
29/29 - 0s - loss: 0.6583 - accuracy: 0.6779
Epoch 14/70
29/29 - 0s - loss: 0.6532 - accuracy: 0.6975
Epoch 15/70
29/29 - 0s - loss: 0.6478 - accuracy: 0.7073
Epoch 16/70
29/29 - 0s - loss: 0.6423 - accuracy: 0.7084
Epoch 17/70
29/29 - 0s - loss: 0.6368 - accuracy: 0.7127
Epoch 18/70
29/29 - 0s - loss: 0.6314 - 

In [22]:
model.predict_classes(scaled_X_test)

C:\Users\Dell\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
    

In [23]:
model.metrics_names

['loss', 'accuracy']

In [29]:
from sklearn.metrics import confusion_matrix,classification_report

In [30]:
predictions=model.predict_classes(scaled_X_test)

In [31]:
predictions

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
    

In [32]:
confusion_matrix(y_test,predictions)


array([[247,  10],
       [ 30, 166]], dtype=int64)

In [34]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.89      0.96      0.93       257
         1.0       0.94      0.85      0.89       196

    accuracy                           0.91       453
   macro avg       0.92      0.90      0.91       453
weighted avg       0.91      0.91      0.91       453



In [35]:
model.save('bank_note_data_model.h5')

In [36]:
from tensorflow.keras.models import load_model

In [37]:
newmodel=load_model('bank_note_data_model.h5')

In [38]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
    